name: "Artifact upload in Artifactory"
description: "This will upload artifact into the desired Artifactory location"
author: "Trideep Nag <trideepnag@gmail.com>"
inputs:
  USER_NAME:  
    description: 'Username to login with'
    required: false
  PASSWORD:
    description: 'Password of the Username used for login'
    required: false
  FILE:
    description: 'Artifact location'
    required: false
  REGISTRY:
    description: 'Desired Artifactory URL'
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
